#!/usr/bin/env bash
# pings an ip address received sa a string argument 5 times else displays
# Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed

if [ "$#" -eq 0 ]
then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
  ping -c 5 "$1"
fi
