#!/usr/bin/env bash
# manages a process , starts stopes and restarts based on commands

PID_FILE="/var/run/my_process.pid"

start() {
    if [ -f "$PID_FILE" ]; then
        echo "Error: manage_my_process is already running."
        exit 1
    fi
    
    echo "Starting manage_my_process..."
    ./manage_my_process &
    PID=$!
    echo $PID > $PID_FILE
    echo "manage_my_process started."
}

stop() {
    if [ ! -f "$PID_FILE" ]; then
        echo "Error: manage_my_process is not running."
        exit 1
    fi
    
    echo "Stopping manage_my_process..."
    PID=$(cat $PID_FILE)
    kill "$PID"
    rm -f $PID_FILE
    echo "manage_my_process stopped."
}

restart() {
    stop
    start
    echo "manage_my_process restarted."
}

usage() {
    echo "Usage: $0 {start|stop|restart}"
    exit 1
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        usage
        ;;
esac

